//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourses
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public int IdCourse { get; set; }
        public System.DateTime Registered { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
